Re run marginalised gaussian notebook
pymc-devs/pymc-examples pull request #4
Opened 2020-12-16 18:16 UTC by MarcoGorelli

Use inferencedata, use `pm.transforms.ordered` to address non-identifiability

2020-12-19 10:57 UTC, AlexAndorra commented
Is this ready for review?

2020-12-19 12:11 UTC, MarcoGorelli commented
@AlexAndorra yup!

2020-12-19 12:35 UTC, AlexAndorra requested changes
Just a small change to make it even better, and then it'll be ready for merge 😉

2020-12-20 21:57 UTC, AlexAndorra approved these changes

2020-12-20 21:58 UTC, merged