Notebook: sampler_stats; update links, clean up sections
pymc-devs/pymc-examples pull request #426
Opened 2022-09-28 16:53 UTC by reshamas

# References
- Towards #394
- References [pymc-devs/pymc #5460](https://github.com/pymc-devs/pymc/issues/5460) (Update example gallery style and formatting)
- References Project Board: https://github.com/pymc-devs/pymc-examples/projects/1

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue: a tracker one for existing notebooks or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

### Notes for the Reviewer
- made some minor updates to the notebook, to be consistent with other notebooks and the style guide.

#DataUmbrellaPyMCSprint

2022-09-30 15:39 UTC, cluhmann commented on examples/diagnostics_and_criticism/sampler-stats.ipynb
>      "(sampler_stats)=\n",
<p>Is there a "keyword" way to reference/link to this bit of documentation?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/426/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2022-09-30 17:12 UTC, OriolAbril requested changes
This notebook is currently being excluded from pre-commit checks: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml#L71. One of the comments below fixes a reference that was a url to our own docs, but we should remove this from the exceptions and check there are no more urls that should be references

2022-09-30 17:12 UTC, OriolAbril commented on myst_nbs/diagnostics_and_criticism/sampler-stats.myst.md
> +- `Note`: NUTS provides the following statistics (these are internal statistics that the sampler uses, you don't need to do anything with them when using PyMC, to learn more about them, [`pymc.NUTS`]
```suggestion
- `Note`: NUTS provides the following statistics (these are internal statistics that the sampler uses, you don't need to do anything with them when using PyMC, to learn more about them, {class}`pymc.NUTS`
```

Note: should probably do the change locally in the notebook, not accept the suggestion here.

2022-09-30 17:12 UTC, OriolAbril commented on myst_nbs/diagnostics_and_criticism/sampler-stats.myst.md
> +* Moved from pymc to pymc-examples repo in December 2020 ([pymc-examples#8](https://github.com/pymc-devs/pymc-examples/pull/8))
I would not include this here

2022-11-05 20:44 UTC, OriolAbril commented
related to https://github.com/pymc-devs/pymc-examples/issues/46

2022-11-05 21:50 UTC, OriolAbril approved these changes

2022-11-05 21:50 UTC, merged