Replace at -> pt.
pymc-devs/pymc-examples pull request #485
Opened 2022-12-27 17:37 UTC by twiecki

Following https://github.com/pymc-devs/pymc-examples/pull/481, now also renaming at->pt. This is the script:

```bash
#!/bin/bash

if [ -z "$1" ]
  then
    echo "Script to automatically convert code (*.py and *.ipynb) from PyMC3 to 4.0. Use with care."
    echo "Usage: pymc3_to_4.sh <path>"
    exit 1
fi

declare -a replace_strings=(
    "s/import pytensor\.tensor as at/import pytensor.tensor as pt/g"
     #"s/tt\./pt./g"
     "s/at\./pt./g"
)

for replace in "${replace_strings[@]}"; do
    find $1 -name "*.ipynb" -type f -exec sed -i -e "/png/n;/stat/n;/that/n;$replace" {} \;
done
```

2022-12-27 19:37 UTC, Armavica requested changes

2022-12-27 19:37 UTC, Armavica commented on examples/case_studies/wrapping_jax_function.ipynb
>      "            at.as_tensor_variable(logp_initial_state),\n",
For some reason this wasn't replaced

2022-12-27 19:37 UTC, Armavica commented on examples/case_studies/wrapping_jax_function.ipynb
>      "            at.as_tensor_variable(logp_initial_state),\n",
Also this

2022-12-27 19:37 UTC, Armavica commented on examples/case_studies/wrapping_jax_function.myst.md
>              at.as_tensor_variable(logp_initial_state),
Here too

2022-12-27 19:37 UTC, Armavica commented on examples/case_studies/wrapping_jax_function.myst.md
>              at.as_tensor_variable(logp_initial_state),
And here

2022-12-28 13:45 UTC, drbenvincent reviewed
Can probably change (or remove) these lines in `rerun.py`
```
"tt.": "at.",
"aet": "at",
```

2022-12-28 13:48 UTC, drbenvincent commented
There's also this in `conf.py`
```
intersphinx_mapping = {
    "aesara": ("https://aesara.readthedocs.io/en/latest/", None),
```

and this in `.pre-commit-config.yaml`
```
      entry: >
          (?x)(arviz-devs.github.io|
               aesara.readthedocs.io|
```

2022-12-28 21:40 UTC, OriolAbril reviewed
left minor comment, other than that looks good. But I have not gone through the replaces carefully, only skimming

2022-12-28 21:41 UTC, OriolAbril commented on examples/conf.py
> +    "pytensor": ("https://pytensor.readthedocs.io/en/latest/", None),
We should remove aesara from this dict and replace it with pytensor instead of adding pytensor. Same goes for the pre-commit config

2022-12-28 22:58 UTC, OriolAbril approved these changes

2022-12-28 23:03 UTC, merged