External nuts sampler
pymc-devs/pymc-examples pull request #560
Opened 2023-07-11 15:54 UTC by twiecki

# Update previous JAX sampling NB

The previous NB was very outdated, I changed the example to be PPCA and update to use`nuts_sampler` kwarg.

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [ ] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

@aseyboldt nutpie is kinda slow on this example, not sure why.

2023-07-11 18:15 UTC, aseyboldt commented
Looks like this model is pretty much a benchmark of the matrix multiply speed in the different backends.
For me all three samplers take about 15s with MKL. What blas do you have installed?

I also get warnings from the numba backend:

```
/home/adr/git/nuts-py/python/nutpie/compile_pymc.py:364: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (Array(float64, 2, 'A', False, aligned=True), Array(float64, 2, 'C', False, aligned=True))
  return inner(x)
/home/adr/git/nuts-py/python/nutpie/compile_pymc.py:364: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (Array(float64, 2, 'C', False, aligned=True), Array(float64, 2, 'A', False, aligned=True))
```

Maybe the ordered transform introduces some non-contigous arrays?

2023-07-11 18:21 UTC, aseyboldt commented
@twiecki Could you maybe check what you get for sampling time alone and compile time alone for numba?

Ie
```
import nutpie

compiled = nutpie.compile_pymc_model(PPCA)
%time nutpie.sample(compiled)
```

We should also use a fixed seed in the notebook, otherwise the data will be different each time we execute it. For me neither of the samplers ends up with a converged posterior,  which makes comparing the times pretty pointless, but that might just be because of the seed I used...

2023-07-11 18:43 UTC, twiecki commented
I added a seed.

compilation time is rather low for this model.

Wall time: 33.4 s for compilation + sampling vs 47s for just sampling.

2023-07-13 14:47 UTC, OriolAbril requested changes
Note: I have commented on the myst file, but make the changes to the ipynb file

2023-08-22 14:45 UTC, twiecki commented
@OriolAbril I have implemented the requested changes.

2023-08-31 13:00 UTC, merged