Update example notebook for mediation analysis to correct package name to PyMC #574
pymc-devs/pymc-examples pull request #576
Opened 2023-09-16 15:43 UTC by asarjou

#574 
 
Updating the mediation_analysis notebook to update the markdown to correct the package name. 

When rerunning the notebook, seaborn raised some Future warnings which were suppressed using the warnings package

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

2023-09-27 11:23 UTC, drbenvincent requested changes
Thanks very much for the contribution @asarjou.

Looks good. There are a few minor changes to some unrelated files which I think snuck in there by accident.

According to the [style guide](https://www.pymc.io/projects/docs/en/latest/contributing/jupyter_style.html) can you change the watermark to:
```python
%load_ext watermark
%watermark -n -u -v -iv -w -p pytensor,xarray
```

I'm not sure if there's a specific policy about suppression of warnings. If it's easy to update the arviz calls to avoid those (and need for warning suppression) then that would be ideal. Any thoughts @OriolAbril?

Could you also add a concise description of the changes made in the Author section? See [here](https://www.pymc.io/projects/docs/en/latest/contributing/jupyter_style.html#authorship-and-attribution) in the style guide.

2023-09-27 11:23 UTC, drbenvincent commented on examples/case_studies/nyc_bym.ipynb
Change to this file seems unrelated to the mediation analysis notebook, can we get rid of this change?

2023-09-27 11:23 UTC, drbenvincent commented on examples/case_studies/nyc_bym.myst.md
Change to this file seems unrelated to the mediation analysis notebook, can we get rid of this change?

2023-09-27 11:23 UTC, drbenvincent commented on examples/howto/model_builder.ipynb
Change to this file seems unrelated to the mediation analysis notebook, can we get rid of this change?

2023-09-27 11:23 UTC, drbenvincent commented on examples/howto/model_builder.myst.md
Change to this file seems unrelated to the mediation analysis notebook, can we get rid of this change?

2023-09-28 12:02 UTC, OriolAbril commented
> I'm not sure if there's a specific policy about suppression of warnings. If it's easy to update the arviz calls to avoid those (and need for warning suppression) then that would be ideal. Any thoughts @OriolAbril?

Warnings should be fixed instead of ignored. Only if there are some issues with trying to fix it (e.g. needing a dependency to be updated or a release to happen) they should be ignored.

@asarjou if you share the complete warning you got from seaborn we might be able to help with its fix.

2023-09-28 12:18 UTC, OriolAbril commented
Saw some seaborn warnings in a different PR. Using the latest release candidate should fix them if they are the same: https://github.com/mwaskom/seaborn/releases/tag/v0.13.0rc0

2024-08-01 20:49 UTC, OriolAbril commented
the pymc3->pymc change has already been fixed, I'll close the PR and issue.

2024-08-01 20:49 UTC, closed without merging